const states = [
  'aguascalientes',
  'baja-california',
  'baja-california-sur',
  'campeche',
  'chiapas',
  'chihuahua',
  'ciudad-de-mexico',
  'coahuila',
  'colima',
  'durango',
  'guanajuato',
  'guerrero',
  'hidalgo',
  'jalisco',
  'mexico',
  'michoacan',
  'morelos',
  'nayarit',
  'nuevo-leon',
  'oaxaca',
  'puebla',
  'queretaro',
  'quintana-roo',
  'san-luis-potosi',
  'sinaloa',
  'sonora',
  'tabasco',
  'tamaulipas',
  'tlaxcala',
  'veracruz',
  'yucatan',
  'zacatecas',
];

module.exports = states;
